// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#include "fb/flush-bgr.hpp"
#include "fb/flush-cases.hpp"
#include "fb/flush-loop.hpp"
#include "fb/flush-rgb.hpp"
#include "fb/flush-rgb565.hpp"
#include "fb/private.hpp"
