// This file is automatically generated, please do not modify it.
#pragma once
enum class PixFmt : u32 {
  RGB,
  BGR,
  RGBA,
  BGRA,
};
namespace pl2d {
enum class MyEnum : i32 {
  Node1,
  Node2 = 3,
};
#if A
enum class A {
  A,
  B,
  C,
};
#endif
};
#define MY_MACRO 内容
#if defined(MY_MACRO)
#define MY_ANOTHER_MACRO 内容 
#endif