// This file is automatically generated, please do not modify it.
#pragma once
typedef enum PixFmt {
  PixFmt_RGB,
  PixFmt_BGR,
  PixFmt_RGBA,
  PixFmt_BGRA,
} PixFmt;
typedef enum PL2D_MyEnum {
  PL2D_MyEnum_Node1,
  PL2D_MyEnum_Node2 = 3,
} PL2D_MyEnum;
#if A
typedef enum PL2D_A {
  PL2D_A_A,
  PL2D_A_B,
  PL2D_A_C,
} PL2D_A;
#endif
#define MY_MACRO 内容
#if defined(MY_MACRO)
#define MY_ANOTHER_MACRO 内容 
#endif