// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "dosldr/8295a.h"
#include "dosldr/ahci.h"
#include "dosldr/cmos.h"
#include "dosldr/cpu.h"
#include "dosldr/debug.h"
#include "dosldr/dma.h"
#include "dosldr/fat.h"
#include "dosldr/fdc.h"
#include "dosldr/file.h"
#include "dosldr/ide.h"
#include "dosldr/kbd.h"
#include "dosldr/list.h"
#include "dosldr/mem.h"
#include "dosldr/pci.h"
#include "dosldr/pfs.h"
#include "dosldr/screen.h"
#include "dosldr/str.h"
#include "dosldr/tsk.h"
#include "dosldr/vdisk.h"
#include "dosldr/vfs.h"
#ifdef __cplusplus
}
#endif
