// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "ELF/ELF.h"
#include "ELF/header.h"
#include "ELF/pt.h"
#include "ELF/sht.h"
#ifdef __cplusplus
}
#endif
