// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "c/color.h"
#include "c/crypto.h"
#include "c/errno.h"
#include "c/error.h"
#include "c/file.h"
#include "c/math/base.h"
#include "c/math/bits.h"
#include "c/math/complex/base.h"
#include "c/math/complex/fft.h"
#include "c/math/exp-log.h"
#include "c/math/math.h"
#include "c/math/sqrt.h"
#include "c/rbtree.h"
#include "c/string.h"
#include "c/syscall.h"
#ifdef __cplusplus
}
#endif
