// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#include "pl2d/ctx.hpp"
#include "pl2d/fb.hpp"
#include "pl2d/matrix.hpp"
#include "pl2d/pixel/define.hpp"
#include "pl2d/pixel/op.hpp"
#include "pl2d/pixel/pixel.hpp"
#include "pl2d/pixel/using.hpp"
#include "pl2d/point.hpp"
#include "pl2d/points/col.hpp"
#include "pl2d/points/line.hpp"
#include "pl2d/points/rect.hpp"
#include "pl2d/points/row.hpp"
#include "pl2d/texture/get-set.hpp"
#include "pl2d/texture/paste.hpp"
#include "pl2d/texture/texture.hpp"
#include "pl2d/texture/trans.hpp"
