// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#include "texture/get-set.hpp"
#include "texture/paste.hpp"
#include "texture/texture.hpp"
#include "texture/trans.hpp"
