timeout: 0
interface_branding: Plant OS x86_64

/Plant OS x86_64
protocol: limine
path: boot():/boot/kernel.bin
module_path: boot():/boot/initramfs.img
module_string: initramfs
resolution: 1024x768x32
