SDL_ROOT ?= .
SDL_SOURCE_DIRS := src \
  src/atomic \
  src/audio \
  src/camera \
  src/core \
  src/cpuinfo \
  src/dynapi \
  src/events \
  src/io \
  src/filesystem \
  src/gpu \
  src/joystick \
  src/haptic \
  src/hidapi \
  src/locale \
  src/main \
  src/misc \
  src/power \
  src/render \
  src/sensor \
  src/stdlib \
  src/storage \
  src/thread \
  src/time \
  src/timer \
  src/video \
  src/dialog \
  src/process \
  src/tray \
  src/audio/dummy \
  src/camera/dummy \
  src/io/generic \
  src/filesystem/dummy \
  src/joystick/dummy \
  src/haptic/dummy \
  src/loadso/dummy \
  src/locale/dummy \
  src/misc/dummy \
  src/sensor/dummy \
  src/render/software \
  src/storage/generic \
  src/thread/generic \
  src/video/yuv2rgb \
  src/dialog/dummy \
  src/process/dummy \
  src/tray/dummy \
  src/timer/plos \
  src/video/plos \
  src/time/plos
SDL_SOURCES := $(foreach dir,$(SDL_SOURCE_DIRS),$(wildcard $(SDL_ROOT)/$(dir)/*.c))
