// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "kernel/acpi.h"
#include "kernel/cmos.h"
#include "kernel/config.h"
#include "kernel/cpu.h"
#include "kernel/debug.h"
#include "kernel/dos.h"
#include "kernel/driver.h"
#include "kernel/fifo.h"
#include "kernel/fs.h"
#include "kernel/gdtidt.h"
#include "kernel/ide.h"
#include "kernel/input_stack.h"
#include "kernel/kbd.h"
#include "kernel/list.h"
#include "kernel/mm.h"
#include "kernel/mouse.h"
#include "kernel/net/arp.h"
#include "kernel/net/dhcp.h"
#include "kernel/net/dns.h"
#include "kernel/net/ftp.h"
#include "kernel/net/http.h"
#include "kernel/net/ipv4.h"
#include "kernel/net/net.h"
#include "kernel/net/ntp.h"
#include "kernel/net/socket.h"
#include "kernel/page.h"
#include "kernel/pci.h"
#include "kernel/pcnet.h"
#include "kernel/pic.h"
#include "kernel/sb16.h"
#include "kernel/screen.h"
#include "kernel/sheet.h"
#include "kernel/signal.h"
#include "kernel/task.h"
#include "kernel/timer.h"
#include "kernel/tty.h"
#include "kernel/vbe.h"
#include "kernel/vdisk.h"
#include "kernel/vga.h"
#ifdef __cplusplus
}
#endif
