default : Makefile
	make -r -C libp
	make -r -C zlib
	make -r -C libtcc1
	make -r -C miniset
	make -r -C bainian
	make -r -C bitz
	make -r -C calc
	make -r -C aigobang
	make -r -C randnum
	make -r -C cale
	make -r -C pfn
	make -r -C sort
	make -r -C copy
	make -r -C pwsh
	make -r -C snake
	make -r -C cgobang
	make -r -C brainfuck
	make -r -C edit
	make -r -C cc
	make -r -C basic
	make -r -C setup1
	make -r -C Maze
	make -r -C clock
	make -r -C nettest
	make -r -C editor
	make -r -C lua
	make -r -C ttf
	make -r -C c4
	make -r -C image
	make -r -C uname
	make -r -C bim2hrb
	make -r -C lox
	make -r -C tcc
	make -r -C psh
	make -r -C tccinst
	make -r -C doomcpy
	make -r -C doomgeneric
	make -r -C minizip
	make -r -C duktape
	make -r -C mmake
clean :
	rm libs/*
	rm out/*

