default : Makefile
	mkdir -p libs
	mkdir -p out
	make -r -C libp
	make -r -C libtcc1
	make -r -C plui
	make -r -C zlib
	make -r -C miniset
	make -r -C sdl2
	make -r -C sdl2_old
	make -r -C freetype
	make -r -C SDL2_ttf
	make -r -C bainian
	make -r -C calc
	make -r -C aigobang
	make -r -C randnum
	make -r -C cal
	make -r -C pfn
	make -r -C sort
	make -r -C copy
	make -r -C pwsh
	make -r -C snake
	make -r -C cgobang
	make -r -C brainfuck
	make -r -C edit
	make -r -C cc
	make -r -C basic
	make -r -C setup1
	make -r -C Maze
	make -r -C clock
	make -r -C nettest
	make -r -C editor
	make -r -C lua
	make -r -C ttf
	make -r -C c4
	make -r -C image
	make -r -C uname
	make -r -C bim2hrb
	make -r -C lox
	make -r -C tcc
	make -r -C psh
	make -r -C tccinst
	make -r -C doomcpy
	make -r -C doomgeneric
	make -r -C minizip
	make -r -C duktape
	make -r -C mmake
	make -r -C init
	cd libutf && make && cd ..
	make -r -C gui
	make -r -C nk
	make -r -C lite-1.11
	make -r -C nasm-master
	make -r -C hexview
	make -r -C kcube
	make -r -C invader
	make -r -C libpng
	make -r -C jpeg
	make -r -C SDL2_image
	make -r -C chat
	make -r -C paint
	make -r -C minewep
	make -r -C bitz
	make -r -C netgobang
	makr -r -C bfpp
clean :
	rm libs/*
	rm out/*

