NASM_ROOT ?= .
NASM_SOURCES := $(NASM_ROOT)/stdlib/snprintf.c \
  $(NASM_ROOT)/stdlib/vsnprintf.c \
  $(NASM_ROOT)/stdlib/strlcpy.c \
  $(NASM_ROOT)/stdlib/strnlen.c \
  $(NASM_ROOT)/stdlib/strrchrnul.c \
  $(NASM_ROOT)/nasmlib/ver.c \
  $(NASM_ROOT)/nasmlib/alloc.c \
  $(NASM_ROOT)/nasmlib/asprintf.c \
  $(NASM_ROOT)/nasmlib/errfile.c \
  $(NASM_ROOT)/nasmlib/crc32.c \
  $(NASM_ROOT)/nasmlib/crc64.c \
  $(NASM_ROOT)/nasmlib/md5c.c \
  $(NASM_ROOT)/nasmlib/string.c \
  $(NASM_ROOT)/nasmlib/nctype.c \
  $(NASM_ROOT)/nasmlib/file.c \
  $(NASM_ROOT)/nasmlib/mmap.c \
  $(NASM_ROOT)/nasmlib/ilog2.c \
  $(NASM_ROOT)/nasmlib/realpath.c \
  $(NASM_ROOT)/nasmlib/path.c \
  $(NASM_ROOT)/nasmlib/filename.c \
  $(NASM_ROOT)/nasmlib/rlimit.c \
  $(NASM_ROOT)/nasmlib/zerobuf.c \
  $(NASM_ROOT)/nasmlib/readnum.c \
  $(NASM_ROOT)/nasmlib/bsi.c \
  $(NASM_ROOT)/nasmlib/rbtree.c \
  $(NASM_ROOT)/nasmlib/hashtbl.c \
  $(NASM_ROOT)/nasmlib/raa.c \
  $(NASM_ROOT)/nasmlib/saa.c \
  $(NASM_ROOT)/nasmlib/strlist.c \
  $(NASM_ROOT)/nasmlib/perfhash.c \
  $(NASM_ROOT)/nasmlib/badenum.c \
  $(NASM_ROOT)/common/common.c \
  $(NASM_ROOT)/x86/insnsa.c \
  $(NASM_ROOT)/x86/insnsb.c \
  $(NASM_ROOT)/x86/insnsd.c \
  $(NASM_ROOT)/x86/insnsn.c \
  $(NASM_ROOT)/x86/regs.c \
  $(NASM_ROOT)/x86/regvals.c \
  $(NASM_ROOT)/x86/regflags.c \
  $(NASM_ROOT)/x86/regdis.c \
  $(NASM_ROOT)/x86/disp8.c \
  $(NASM_ROOT)/x86/iflag.c \
  $(NASM_ROOT)/asm/error.c \
  $(NASM_ROOT)/asm/floats.c \
  $(NASM_ROOT)/asm/directiv.c \
  $(NASM_ROOT)/asm/directbl.c \
  $(NASM_ROOT)/asm/pragma.c \
  $(NASM_ROOT)/asm/assemble.c \
  $(NASM_ROOT)/asm/labels.c \
  $(NASM_ROOT)/asm/parser.c \
  $(NASM_ROOT)/asm/preproc.c \
  $(NASM_ROOT)/asm/quote.c \
  $(NASM_ROOT)/asm/pptok.c \
  $(NASM_ROOT)/asm/listing.c \
  $(NASM_ROOT)/asm/eval.c \
  $(NASM_ROOT)/asm/exprlib.c \
  $(NASM_ROOT)/asm/exprdump.c \
  $(NASM_ROOT)/asm/stdscan.c \
  $(NASM_ROOT)/asm/strfunc.c \
  $(NASM_ROOT)/asm/tokhash.c \
  $(NASM_ROOT)/asm/segalloc.c \
  $(NASM_ROOT)/asm/rdstrnum.c \
  $(NASM_ROOT)/asm/srcfile.c \
  $(NASM_ROOT)/macros/macros.c \
  $(NASM_ROOT)/output/outform.c \
  $(NASM_ROOT)/output/outlib.c \
  $(NASM_ROOT)/output/legacy.c \
  $(NASM_ROOT)/output/nulldbg.c \
  $(NASM_ROOT)/output/nullout.c \
  $(NASM_ROOT)/output/outbin.c \
  $(NASM_ROOT)/output/outaout.c \
  $(NASM_ROOT)/output/outcoff.c \
  $(NASM_ROOT)/output/outelf.c \
  $(NASM_ROOT)/output/outobj.c \
  $(NASM_ROOT)/output/outas86.c \
  $(NASM_ROOT)/output/outdbg.c \
  $(NASM_ROOT)/output/outieee.c \
  $(NASM_ROOT)/output/outmacho.c \
  $(NASM_ROOT)/output/codeview.c \
  $(NASM_ROOT)/disasm/disasm.c \
  $(NASM_ROOT)/disasm/sync.c
