DOOM_ROOT ?= .
DOOM_SOURCES := $(DOOM_ROOT)/dummy.c \
  $(DOOM_ROOT)/am_map.c \
  $(DOOM_ROOT)/doomdef.c \
  $(DOOM_ROOT)/doomstat.c \
  $(DOOM_ROOT)/dstrings.c \
  $(DOOM_ROOT)/d_event.c \
  $(DOOM_ROOT)/d_items.c \
  $(DOOM_ROOT)/d_iwad.c \
  $(DOOM_ROOT)/d_loop.c \
  $(DOOM_ROOT)/d_main.c \
  $(DOOM_ROOT)/d_mode.c \
  $(DOOM_ROOT)/d_net.c \
  $(DOOM_ROOT)/f_finale.c \
  $(DOOM_ROOT)/f_wipe.c \
  $(DOOM_ROOT)/g_game.c \
  $(DOOM_ROOT)/hu_lib.c \
  $(DOOM_ROOT)/hu_stuff.c \
  $(DOOM_ROOT)/info.c \
  $(DOOM_ROOT)/i_cdmus.c \
  $(DOOM_ROOT)/i_endoom.c \
  $(DOOM_ROOT)/i_joystick.c \
  $(DOOM_ROOT)/i_scale.c \
  $(DOOM_ROOT)/i_sound.c \
  $(DOOM_ROOT)/i_system.c \
  $(DOOM_ROOT)/i_timer.c \
  $(DOOM_ROOT)/memio.c \
  $(DOOM_ROOT)/m_argv.c \
  $(DOOM_ROOT)/m_bbox.c \
  $(DOOM_ROOT)/m_cheat.c \
  $(DOOM_ROOT)/m_config.c \
  $(DOOM_ROOT)/m_controls.c \
  $(DOOM_ROOT)/m_fixed.c \
  $(DOOM_ROOT)/m_menu.c \
  $(DOOM_ROOT)/m_misc.c \
  $(DOOM_ROOT)/m_random.c \
  $(DOOM_ROOT)/p_ceilng.c \
  $(DOOM_ROOT)/p_doors.c \
  $(DOOM_ROOT)/p_enemy.c \
  $(DOOM_ROOT)/p_floor.c \
  $(DOOM_ROOT)/p_inter.c \
  $(DOOM_ROOT)/p_lights.c \
  $(DOOM_ROOT)/p_map.c \
  $(DOOM_ROOT)/p_maputl.c \
  $(DOOM_ROOT)/p_mobj.c \
  $(DOOM_ROOT)/p_plats.c \
  $(DOOM_ROOT)/p_pspr.c \
  $(DOOM_ROOT)/p_saveg.c \
  $(DOOM_ROOT)/p_setup.c \
  $(DOOM_ROOT)/p_sight.c \
  $(DOOM_ROOT)/p_spec.c \
  $(DOOM_ROOT)/p_switch.c \
  $(DOOM_ROOT)/p_telept.c \
  $(DOOM_ROOT)/p_tick.c \
  $(DOOM_ROOT)/p_user.c \
  $(DOOM_ROOT)/r_bsp.c \
  $(DOOM_ROOT)/r_data.c \
  $(DOOM_ROOT)/r_draw.c \
  $(DOOM_ROOT)/r_main.c \
  $(DOOM_ROOT)/r_plane.c \
  $(DOOM_ROOT)/r_segs.c \
  $(DOOM_ROOT)/r_sky.c \
  $(DOOM_ROOT)/r_things.c \
  $(DOOM_ROOT)/sha1.c \
  $(DOOM_ROOT)/sounds.c \
  $(DOOM_ROOT)/statdump.c \
  $(DOOM_ROOT)/st_lib.c \
  $(DOOM_ROOT)/st_stuff.c \
  $(DOOM_ROOT)/s_sound.c \
  $(DOOM_ROOT)/tables.c \
  $(DOOM_ROOT)/v_video.c \
  $(DOOM_ROOT)/wi_stuff.c \
  $(DOOM_ROOT)/w_checksum.c \
  $(DOOM_ROOT)/w_file.c \
  $(DOOM_ROOT)/w_main.c \
  $(DOOM_ROOT)/w_wad.c \
  $(DOOM_ROOT)/z_zone.c \
  $(DOOM_ROOT)/w_file_stdc.c \
  $(DOOM_ROOT)/i_input.c \
  $(DOOM_ROOT)/i_video.c \
  $(DOOM_ROOT)/doomgeneric.c \
  $(DOOM_ROOT)/doomgeneric_sdl.c \
  $(DOOM_ROOT)/mus2mid.c
